### ISSUE TITLE
Check if ZFS tank exists on startup

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#115]
Add check if zfs tank "bastille" exists during "service start".
Otherwise bootstrap will fail with the following error (parent does not exist)

> bastille bootstrap 12.1-RELEASE
> cannot create 'zroot/bastille/backups': parent does not exist

Any suggestions where to put it? bastille(.sh)?

**Comment by cedwards** [comment]
I ran into this issue today and guess the cause was installation via `make install`?

The addition we made to the Makefile creates the `/usr/local/bastille` and sets perms, but that is a primary directory we check to ensure bootstrap has happened.

Removing the entry creating the directory from the Makefile _should_ avoid this issue. It will require a post-bootstrap chmod on the dirs afterwards, as it did before.
