### ISSUE TITLE
[ENHANCEMENT] (minor) check if bastille0 exists on startup

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#128]
### Add a double check if bastille0 exists in `start.sh`.

(not actual code)
```
if [ ! ifconfig | grep $bastille_jail_interface> /dev/null] than
echo "Interface bastille0 not found. See Docs/Network Requirements" # or something like that
```

### error message if bastille0 doesn't exist:
ifconfig: interface bastille0 does not exist
jail: esfrasltj1: /sbin/ifconfig bastille0 inet 10.0.0.1 netmask 255.255.255.255 alias: failed
**jls: jail "jail_test_lo1" not found**

**Comment by hackacad** [comment]
I'll create a PR if you agree with the proposed solution (small lint at "ip check" fixed as well):
https://github.com/BastilleBSD/bastille/commit/52dbf2310f3ece89815d6dc58224cb9409548699

**Comment by cedwards** [comment]
I think the proper solution for this (and for the ip6) is determine the containers `interface=` and check that it is created and up. The `${bastille_jail_interface}` may not always be the interface assigned.

**Comment by X86BSD** [comment]
I was just getting ready to file some enhancement requests. This was one of them.
It's not just on startup though it should be done during 'bastille create', because you create the jail before you start it, it seems that putting the check in 'start' is incorrect it should be in 'create.sh'. I can create bastille jails without setting the interface in /etc/rc.conf and it will create the jail, but upon start it errors out with: 

> doas bastille start ALL
[bastilletest]:
jail: bastilletest: jail_set: Invalid argument
jls: jail "bastilletest" not found

And a 'bastille list' shows nothing. It cannot see the jail that was created.
