### ISSUE TITLE
VNET enabled jails no IP address found for -

### ISSUE THREAD

**Issue by Johanhen** [BastilleBSD/bastille#165]
When starting or stopping a VNET jail we get the error no IP address found for -

root@test01-head:~/projects/bastillebsd/bastille # bastille start vnetjail3
[vnetjail3]:
e0a_bastille3
e0b_bastille3
vnetjail3: created
no IP address found for -

And a stop
root@test01-head:~/projects/bastillebsd/bastille # bastille stop vnetjail5
no IP address found for -
[vnetjail5]:
vnetjail5: removed

This is from pfctl which can not find the IP address. from the command $(jls -j ${_jail} ip4.addr).

**Comment by cedwards** [comment]
We can work on suppressing this output, but to some extent it is expected.

Because VNET-enabled containers fully manage their own interface and IP information this data can't be (without some work) reported by Bastille. Even underlying tools such as `jls` will also lack IP information for VNET containers.

**Comment by Johanhen** [comment]
First off all, thank you for your time and effort in creating a nice and simple jail configuration tool.

I think VNET makes things a little more complex.
For people who set a public facing IP address to the jail, they do not need the pf from the host, so they can bypass the pf commands.
For some who want to use the host firewall, pf needs to be fed with the IP address.
If we create a jail, maybe we can set a switch for that jail to either use or not use the host firewall.
To get  the IP address we maybe can use jexec
jexec vnetjail ifconfig vnet0 | awk '$1 == "inet" { print $2 }'

**Comment by electrohad** [comment]
Hello 

it's not perfect because if the ip4.add is empty, it will return the previous answer something to fix with awk and getline 
It's print the 1st line, and after if ther is 3 field (VNET usage) it will parse the conf file to look for the IP. In case of 4 fields it doesn't touch the line 


jls | awk '{if ( NR>1 && (NF != 4)){directory ="dirname "$3; directory | getline y ;y = y"/jail.conf";file ="pcregrep -so1 '\''ip4.addr = (.*);'\'' "y;file | getline x jls | awk '{if ( NR>1 && (NF != 4)){directory ="dirname "$3; directory | getline y ;y = y"/jail.conf";file ="pcregrep -so1 '\''ip4.addr = (.*);'\'' "y;file | getline x;print $1,x,$2,$3,y,file} else if ( NR>1 && NF == 4) {print "$0"}}';print $1,x,$2,$3,y,file} else if ( NR>1 && NF == 4) {print "$0"}}'

**Comment by cedwards** [comment]
This is addressed in #376

**Comment by cedwards** [comment]
Considering this addressed with the merge of #376.
