### ISSUE TITLE
bootstrap fails to set secure permissions in ZFS

### ISSUE THREAD

**Issue by va83** [BastilleBSD/bastille#175]
In ZFS filesystem the command
`bastille bootstrap 12.1-RELEASE update`
fails to update release with error message
```
Insecure permissions on /usr/local/bastille  
Try: chmod 0750 /usr/local/bastille
```

**Comment by hackacad** [comment]
Is there any error when executing:
> chmod 0750 /usr/local/bastille
as suggested?

The chmod was added in https://github.com/BastilleBSD/bastille/commit/861953734f75240dfa0c84c93ab37e6a7c2ed433#diff-b67911656ef5d18c4ae36cb6741b7965 but had to be reverted due to some side effects (ZFS vs. UFS).

Are you using current Github clone or pkg (stable/latest)?

**Comment by va83** [comment]
`chmod 0750 /usr/local/bastille` executes without error.

Bastille is installed with pkg from latest, version 0.6.20200202

Directly after installation there is no folder `/usr/local/bastille`. This folder is created with `bastille bootstrap`

It seems that `bootstrap_directories()` in `bootstrap.sh` sets correct permissions for UFS but doesn't for ZFS.
