### ISSUE TITLE
[ENHANCEMENT] Default template

### ISSUE THREAD

**Issue by Johanhen** [BastilleBSD/bastille#205]
**Is your feature request related to a problem? Please describe.**
I need to put some extra files on the system, not only /etc/resolve.conf but also my own repo config file like  /usr/local/etc/pkg/repos/poudriere.conf And with that a ssl certificate for poudriere /usr/local/etc/ssl/private and a standard .vim .profile and my ssh authrized_key file, and so on.

**Describe the solution you'd like**
A default template that can be filled with personal config files.
I set it now in my bastille.conf file, a nice adition would be a command line toggle  like -t to include the template.
root@BSD # bastille create -t  jailname 12.1-RELEASE 10.10.9.1 

**Describe alternatives you've considered**
None

**Additional context**
I have made a POC for this and it works for me.

in /usr/local/etc/bastille/bastille.conf i have added the following lines and removed the resolv.conf part because i use my template for this.
```
bastille_default_template="YES"                                       ## default: ""
bastille_default_template_files="${bastille_templatesdir}/default/base" ## default:  
 "${bastille_templatesdir}/default/base"
```
and removed 
```
## default jail resolv.conf
bastille_resolv_conf="/etc/resolv.conf"                               ## default: "/etc/resolv.conf"
```
In /usr/local/share/bastille/create.sh i removed

```
## resolv.conf (default: copy from host)
    if [ ! -f "${bastille_jail_resolv_conf}" ]; then
        cp -L "${bastille_resolv_conf}" "${bastille_jail_resolv_conf}"
```
And replaced it with 
```
     ## Copy files from default template
     if [ ${bastille_default_template+x} ]; then
         echo -e "${COLOR_GREEN}Copy files from default template. ${COLOR_RESET}"
         while read _dir; do
             cp -av "${bastille_default_template_files}/${_dir}" "${bastille_jail_path}" || exit 1
         done < "${bastille_default_template_files}/OVERLAY"
         echo -e "${COLOR_GREEN}[${_jail}]:OVERLAY -- END${COLOR_RESET}"
         echo
```
I also create the default template named base in /usr/local/bastille/templates/default/base
There i have my OVERLAY file and all the files i need on a fresh jail.

For me this works very nice

**Comment by chriswells0** [comment]
I love the general concept of this and would like to hear feedback from @cedwards before creating a PR. I'd like to implement it as a Bastille template so it has all of the associated functionality.  The config parameter would simply provide the template name (or empty to skip):
```
bastille_default_template="bastillebsd-templates/default"
```
All initial customization of the contents of a new jail could be moved from the `create` command into the default template, which could be included in the build so it didn't need to be bootstrapped.

If a user wanted to override the default template, they could create their own and update the variable.  Their template could be completely from scratch or `INCLUDE` the default and extend it.

If you like this approach, please also let me know if #217 will be accepted so I can create a Bastillefile rather than individual hook files for the template.
