### ISSUE TITLE
[BUG] Can't start jail automatically if name contains "-"

### ISSUE THREAD

**Issue by grzs** [BastilleBSD/bastille#244]
I created a jail with name "vpn-gw", and set auto-start. It appeared in the config file bastille_config like this:
vpn-gw_AUTO_START="YES"

After I checked the auto start mechanism in bastille-init script (function ext_start) and tried the command in the shell:
$ sysrc -f bastille_config -n vpn-gw_AUTO_START
output: gw_AUTO_START

I renamed the jail to vpn_gw and the output changed to "YES", and it works as expected.

The problem is that I never saw any warning regarding jail naming, and the Xigmanas extension GUI let me submit the wrong name.

I installed Bastille v0.7.20200714 with OneButtonInstaller on Xigmanas 12.1.0.4 - Ingva (revision 7683).

**Comment by JRGTH** [comment]
Hi, thanks for reporting the bug about jail auto-start on XigmaNAS Bastille Extension.

The problem is indeed with `sysrc` handling names with dashes, I've made a [quick fix](https://github.com/JRGTH/xigmanas-bastille-extension/commit/9932b00a376b705019f767c2a7412cd9f1739b50) and replaced the relevant commands with `sed` instead and is working as expected now.

Regards

**Comment by grzs** [comment]
Great, thanks!

JRGTH <notifications@github.com> ezt írta (időpont: 2020. aug. 26., Sze,
0:43):

**Comment by JRGTH** [comment]
Hi, the auto-start [fix](https://github.com/JRGTH/xigmanas-bastille-extension/commit/cfbf2a4fea81d76f1903629facc1a009244ad902) has also been added to`bastille-init` for the XigmaNAS Bastille Extension.
Regards
