### ISSUE TITLE
[BUG] ZFS to UFS jail import fails

### ISSUE THREAD

**Issue by tofazzz** [BastilleBSD/bastille#265]
Hi there,

I am not sure why but I am exporting a jail from a ZFS 12.1-RELEASE-p10 server and if I try to import it to a UFS 12.1-RELEASE-p10 server I get the following error:

Validating file: frw-mon1_2020-10-14-225212.xz...
File validation successful!
Unsupported archive format.

Bastille 0.7.20200714 on both servers
FreeBSD 12.1-RELEASE-p10 on both servers

Installed with pkg

Is this export/import not supported or should I change something in the archive?

Thank you!
tofaz

**Comment by JRGTH** [comment]
Hello, you can't import ZFS images into UFS setups, however you can export a jail from an UFS setup and it can be later imported into an ZFS setup, this is more of a **limitation** rather than a **bug**.

Heres is why, ZFS exports are raw data streams performed by `zfs send` from a recent ZFS snapshot and they are imported back with `zfs recv`, meaning they only can be imported back to a bastille setup configured for ZFS, also ZFS exported jails are compressed with the `xz` format.

Regarding UFS exported jails, they are just a standard `txz` (tar.xz) backup archives of the jail root content, they can be imported on UFS setups but they can also be imported in ZFS setups because the script will check/detect if bastille is running under ZFS, then it will create the required ZFS datasets accordingly and the archive will be later extracted on said datasets.

Possible solution/enhancement may be adding either, a confg variable or an extraction option to make bastille configured for ZFS export the jails in a standard `txz` backup archive regardless, though I don't see much use for this IMHO.

Regards

**Comment by tofazzz** [comment]
Thank you for the explanation! I think I got confused as initially this jail was moved from a UFS based system to a ZFS one, and I was trying to achieve the opposite.

I guess it's a lack of my knowledge about the baseline functionalities but checking Bastille's documentation I have not seen any specific mention of this limitation/restriction.

Do you know if there is a workaround to move a jail from a ZFS based system to a UFS ones without reinstalling?

**Comment by JRGTH** [comment]
> Thank you for the explanation! I think I got confused as initially this jail was moved from a UFS based system to a ZFS one, and I was trying to achieve the opposite.
> 
> I guess it's a lack of my knowledge about the baseline functionalities but checking Bastille's documentation I have not seen any specific mention of this limitation/restriction.
> 
> Do you know if there is a workaround to move a jail from a ZFS based system to a UFS ones without reinstalling?

Don't worry, bastille is an ongoing project and there is a lot to be documented in regards its functionality and its limitations ;).

To answer your question, I think the easiest way to move a current ZFS bastille jail to an UFS host is to manually backup the jail content then create an empty jail with the same name of the existing jail on the UFS host, then extract the package there.

**Here is a basic example on how to manually backup an existing jail:**

CD to the jail location, i.e. where the jail root and config files are:
```
root@mserver: ~# cd /mnt/storage/bastille/jails/nginx
```

Then backup the jail content with `tar` 
```
root@mserver: /mnt/storage/bastille/jails/nginx# tar -cvf nginx.tgz *
```

**Here is an example on how to create and emty jail, then extract a previous jail archive:**

In the UFS host, create an empty jail with the name of the original archived jail if possible:
```
root@testmachine: ~# bastille create -E nginx
Creating empty jail: nginx.
```

CD and extract the previous jail archive inside the emty bastille jail on the new host:
```
root@testmachine: ~# cd /mnt/hdd1/bastille/jails/nginx
root@testmachine: /mnt/hdd1/bastille/jails/nginx# tar -xvf nginx.tgz
```

Note that you need to copy/move the previous backup archive to the new host as expected, in case you need to rename the jail you can use `bastille rename` command, and/or manually adjust the configuration files accordingly in regards NAME/NIC/IP, fstab etc. etc. before start the jail.

Regards

**Comment by tofazzz** [comment]
Thank you very much for the workaround! It worked!

I just needed to manually recreate the logs folder and jail's logfile prior to start the copied jail.

**Comment by JRGTH** [comment]
> Thank you very much for the workaround! It worked!
> 
> I just needed to manually recreate the logs folder and jail's logfile prior to start the copied jail.

Hi, thanks for try and confirming it worked for you. :)

P.S. I think I will look into an bastille export option to create a standard tar backup backup on ZFS setups for backward compatibility, it may be useful for some specific case uses as per see.

Regards

**Comment by tofazzz** [comment]
Thank you for your great work and time spent into this project! :)

**Comment by JRGTH** [comment]
> Thank you for your great work and time spent into this project! :)

Hello, PR #267 should address this issue hopefully.

Regards

**Comment by cedwards** [comment]
PR #267 has been merged. Please let us know if this addresses your issue.
