### ISSUE TITLE
Clarification on how EXPORT works.

### ISSUE THREAD

**Issue by Gerard-ODonnell** [BastilleBSD/bastille#304]
Hi,

I'm seeking clarification of ZFS-backed jails that contain multiple processes, for example a postgresql jail.

Because this is on ZFS, I do not need to shut down this jail before running an `export`, but I am wondering if an `import` of this export would perhaps result in an expected state, perhaps because for example a transaction on the database was in progress when the ZFS-snapshot was intiated.

It seems to me the only 100% safe method of doing a backup is to shutdown, `export`, and start up again. I'm wondering if it would be possible to 

1. shutdown
2. snapshot
3. start up
4. export the snapshot
5. delete the snapshot

to minimize downtime of the jail.

I can update the `export` documentation once someone knowledgeable has replied.

**Comment by JRGTH** [comment]
Hi, the bastille `export` command can be executed in running ZFS jails since it will send a `XZ` compressed data stream of the recent snapshot wich is automatically created when executed, then the snapshot will be cleaned after export completes, this will be an exact jail image at that time only and its main purposes is for ease archival and/or distribution, though for jails running web, databases and alike can be safely stopped > exported >  and started.

For filesystems such as UFS, the `export` command always requires the jail to be stopped as expected, the export archive will be `.txz` and can be imported in either ZFS/UFS filesystems.

Note that jails running under ZFS, the `export` command will always sent a resent snapshot data stream piped with `XZ` for reliability and convenience, this exports ending with `.xz` will be importable only on ZFS setups as expected, or even manually extracted for advanced ZFS send/recv purposes as well.

In the event someone need to export a jail from an ZFS setup to later import it into an UFS system, the user can execute `bastille export jail_name -t` or `bastille export jail_name --txz` to create a standard compressed backup archive, again this optional export requires the jail to be stopped as expected.

Export samples

**Exporting a jail from a ZFS system:**
```
root@nas-mserver: ~# bastille export zfs_jail
Exporting 'zfs_jail' to a compressed .xz archive.
Sending ZFS data stream...
  100 %      662.2 KiB / 9324.9 KiB = 0.071                   0:02             
Exported '/mnt/storage/bastille/backups/zfs_jail_2021-01-06-080707.xz' successfully.
```

**Exporting a jail from a ZFS system but request a standard .TXZ archive for import compatibility:**
```
root@nas-mserver: ~# bastille export zfs_jail -t
Exporting 'zfs_jail' to a compressed .txz archive...
  100 %      426.9 KiB / 7340.0 KiB = 0.058                   0:01             
Exported '/mnt/storage/bastille/backups/zfs_jail_2021-01-06-080840.txz' successfully.
```

Also as yerrysherry denoted, user defined incremental ZFS send of big jails is another option, though it may require for user custom scripting/cron and some ZFS knowledge as expected.

Regards

**Comment by Gerard-ODonnell** [comment]
Hi JRGTH,

_..."its main purposes is for ease archival and/or distribution, though for jails running web, databases and alike can be safely stopped > exported > and started."_

OK, this makes sense. Putting aside yerrysherry's valid comment that the database would recover (because there are yet other jails where that isn't the case. My example was poorly chosen) and considering just the case of a jail where you _must_ shutdown first, I was thinking that an improvement to the `export` process for ZFS systems though might be 

1. shutdown
2. snapshot
3. _start up_
4. _export the snapshot_
5. delete the snapshot

instead of 

1. shutdown
2. snapshot
3. _export the snapshot_
4. _start up_
5. delete the snapshot

There is the obvious advantage that there is much less downtime in the first situation. 

I'm not at all proposing that this should replace the current functionality of no-downtime snapshotting on ZFS, but perhaps this can be made _in addition to_. Some kind of flag or something for the export command:

`bastille export -stop_then_snapshot_then_start_then_export jail_name`

or similar. Thoughts?

**Comment by hackacad** [comment]
Adding an additional option (e.g. -s / --secure) sounds good. 

A use-case would be exporting Elasticsearch jails before upgrading them.

**Comment by JRGTH** [comment]
I think this is a very nice idea/addition indeed, an option for a safe/secure export that will care of the exporting process.

So pretty much the safe export would be like: `stop -> snapshot -> start -> export -> snap_cleanup` effectively reducing downtime while exporting safely.

Maybe we could use the options `-s|--safe` which suits more the intended purpose?

Regards

**Comment by JRGTH** [comment]
Hi, as requested this `safe exports` feature is already implemented, however I will hold this PR until get some feedback about the pending PR on the Empty jail issue/fix, some examples below.

**Usage:** `bastille export TARGET [option] | PATH`

**Quickly export a running ZFS jail:**

```
root@nas-mserver: ~# bastille export jail1 
Exporting 'jail1' to a compressed .xz archive.
Creating temporary ZFS snapshot for export...
Sending ZFS data stream...
  100 %      662.0 KiB / 9324.3 KiB = 0.071                   0:02             
Exported '/mnt/storage/bastille/backups/jail1_2021-01-08-081941.xz' successfully.
```

**Safely export a running ZFS jail:**

```
root@nas-mserver: ~# bastille export jail1 -s
Safely exporting 'jail1' to a compressed .xz archive.
[jail1]:
jail1: removed

Creating temporary ZFS snapshot for export...
[jail1]:
jail1: created

Sending ZFS data stream...
  100 %      661.6 KiB / 9320.3 KiB = 0.071                   0:02             
Exported '/mnt/storage/bastille/backups/jail1_2021-01-08-082011.xz' successfully.
```

Regards

**Comment by Gerard-ODonnell** [comment]
Hi JRGTH,

_root@nas-mserver: ~# bastille export jail1 
Exporting 'jail1' to a compressed .xz archive._

_root@nas-mserver: ~# bastille export jail1 -s
Safely exporting 'jail1' to a compressed .xz archive._

Information is provided that we are 'safely' exporting a compressed .xz archive when using `-s` now.  I wonder if it would be helpful to the user to know that they are 'hot' exporting the jail now by default.

i.e. instead of 

_root@nas-mserver: ~# bastille export jail1 
Exporting 'jail1' to a compressed .xz archive._

it could now say
_root@nas-mserver: ~# bastille export jail1 
**Hot** Exporting 'jail1' to a compressed .xz archive._

or

_root@nas-mserver: ~# bastille export jail1 
**Online** Exporting 'jail1' to a compressed .xz archive._

**Comment by JRGTH** [comment]
@Gerard-ODonnell  I Just added the `Hot` part as suggested to the default exporting method so users will be aware of how it behaves.

```
root@nas-mserver: ~# bastille export jail1
Hot exporting 'jail1' to a compressed .xz archive.
Creating temporary ZFS snapshot for export...
Sending ZFS data stream...
  100 %      659.5 KiB / 9322.1 KiB = 0.071                   0:02             
Exported '/mnt/storage/bastille/backups/jail1_2021-01-08-160136.xz' successfully.
```

Regards

**Comment by Gerard-ODonnell** [comment]
Hi JRGTH,

I have modified the `export` documentation.

**Comment by bmac2** [comment]
implemented by @jrgth so closing item.
