### ISSUE TITLE
[BUG] "Unrecognized archive name." when importing ezjail archive

### ISSUE THREAD

**Issue by g-teley** [BastilleBSD/bastille#447]
When importing an ezjail archive (created with ezjail-admin archive jailname) I get an "Unrecognized archive name." error.

``bastille -v && freebsd-version -kru`` output:
0.9.20210714
13.0-RELEASE-p4
13.0-RELEASE-p4
13.0-RELEASE-p4

Bastille installed from PKG

Ezjail creates a .tar.gz archive file. This has been transferred to my 13.0-p4 test machine.
The archive file can be opened/listed by tar with no problems.
Running the command `bastille import jail_archive.tar.gz` gives an error "Unrecognized archive name."

**Comment by JRGTH** [comment]
Hello I've tested the `bastille import` for `ezjail` .tar.gz archives with success, here below are some sample output:

```
root@nas-mserver: ~# bastille list import
apache_2020-02-29-224413.xz
emby_2021-06-12-205410.xz
ez_jail1-202109221715.14.tar.gz
minidlna_2020-05-05-110039.xz
nginx_2020-05-04-204206.xz
plex_2020-05-04-202850.xz
root@nas-mserver: ~# bastille import ez_jail1-202109221715.14.tar.gz
Importing 'ez_jail1' from foreign compressed .tar.gz archive.
Preparing ZFS environment...
Extracting files from 'ez_jail1-202109221715.14.tar.gz' archive...
tar: Removing leading '/' from member names
Generating jail.conf...
Updating symlinks...
Container 'ez_jail1' imported successfully.
root@nas-mserver: ~# bastille start ez_jail1
no IP address found for em0|10.0.0.10
[ez_jail1]:
ez_jail1: created
```

Please look at the `ezjail` archive name tag `ez_jail1-202109221715.14.tar.gz`, since `bastille import` looks for this exact naming, there may be your problem, please rename the archive and re-try the import, this is done on purpose to let `bastille` to import known/tested archives/images from known jail managers, so unsupported jail archives can still be added `bastille` through the "empty" `-E|--empty` jail creation and extracted/configured by hand.

**Example of the auto-configured `jail.conf` from the simple Shared-IP ez_jail1(this may require edit for more complex networking scheme as expected):**
```
ez_jail1 {
  devfs_ruleset = 4;
  enforce_statfs = 2;
  exec.clean;
  exec.consolelog = /var/log/bastille/ez_jail1_console.log;
  exec.start = '/bin/sh /etc/rc';
  exec.stop = '/bin/sh /etc/rc.shutdown';
  host.hostname = ez_jail1;
  mount.devfs;
  mount.fstab = /mnt/storage/bastille/jails/ez_jail1/fstab;
  path = /mnt/storage/bastille/jails/ez_jail1/root;
  securelevel = 2;

  interface = em0;
  ip4.addr = em0|10.0.0.10;
  ip6 = disable;
}
```

**bastille** version: 0.9.20210714
**ezjail** version: v3.4.2

**Comment by g-teley** [comment]
Well, as you said, you have to keep the exact same name as what ezjail gave to it.

The only difference I'm having after importing is that there is no IP address assigned.
  interface = lo1;
  ip4.addr = -;
  ip6 = disable;
But that is a minor issue because one would, in a normal world, assign it a different address anyway.

Thanks for the support!

**Comment by JRGTH** [comment]
> Well, as you said, you have to keep the exact same name as what ezjail gave to it.
> 
> The only difference I'm having after importing is that there is no IP address assigned.
> interface = lo1;
> ip4.addr = -;
> ip6 = disable;
> But that is a minor issue because one would, in a normal world, assign it a different address anyway.
> 
> Thanks for the support!

Hi, thanks for the response and for confirm you were able to import the ezjail container after keeping the default archive naming.

As for the network configuration, since there is several ways to configure this parameters and that the importer try to reads basic shared-IP config from the previous jail manager config files, the user may need to adjust the `jail.conf`accordingly.

Between the import command may be improved in the future and provide a way to let the user specify NIC/IP/VNET on the fly, besides the basic import auto-config.
