### ISSUE TITLE
[Question] TrueNAS / OPNSense 

### ISSUE THREAD

**Issue by ShalokShalom** [BastilleBSD/bastille#506]
Hi there :)

I am interested to do routing and hosting of Nextcloud on one x86 board.

I came to the conclusion, that BSD might do this job, and found appropriate distros, in the form of TrueNAS and OPNSense.

Does Bastille configure Jails particularly trailered for these distros?

And is this even supported at all, to use entire freeBSD instances in Jails?

**Comment by yaazkal** [comment]
I guess you can start looking at this plugin for XigmaNAS: https://github.com/JRGTH/xigmanas-bastille-extension
cc @JRGTH

**Comment by yaazkal** [comment]
Just to keep it clear for people searching this topic in the future:

> Does Bastille configure Jails particularly trailered for these distros?
It's possible, not sure if there are templates at the moment. I only remember one for [NextCloud](https://gitlab.com/bastillebsd-templates/nextcloud). But usually you install OPNSense on the host or XigmaNAS/TrueNAS on the host, and add a Bastille Plugin to manage jails. That's why I referred the XigmaNAS plugin.

> And is this even supported at all, to use entire freeBSD instances in Jails?
A jail can be whatever you want: one single process or an entire FreeBSD system as "isolated" as you want. That always depends on your **configuration**. VNET jails for example adds network isolation. So it's always configuration. I like to think jails as super performant VMs rather than "containers", but is a mix.
