### ISSUE TITLE
[QUESTION] Howto migrate from iocage to bastille

### ISSUE THREAD

**Issue by Bern586** [BastilleBSD/bastille#527]
Wouldn't be interesting to document a small migration procedure/checklist in the documentation to assist those still using iocage, and who wish to migrate to bastille?

Best regards

**Comment by Bern586** [comment]
Some articles are available addressing this scenario
https://hackacad.net/freebsd/2020/03/26/howto-migrate-your-freebsd-jails-from-iocage-to-bastille.html
but an official endorsement could encourage users to switch.
Just my 2¢

**Comment by bmac2** [comment]
How-to migrate your FreeBSD jails from iocage to bastille
Mar 26, 2020
1 min read
Stop the running jail and export it:

iocage stop jailname
iocage export jailname
Move the backup files (.zip and .sha256) into Bastille backup dir (default: /usr/local/bastille/backups/):

mv /iocage/images/jailname_2020-03-26.* /usr/local/bastille/backups/
for remote systems you could use rsync:
rsync -avh /iocage/images/jailname_2020-03-26.* root@10.0.1.10:/usr/local/bastille/backups/
Import the iocage backup file (use zip file name)
bastille import jailname_2020-03-26.zip
```</pr```e>
Set your new ip address and interface:
vim /usr/local/bastille/jails/jailname/jail.conf
interface = bastille0;
ip4.addr = "192.168.0.1";
You can use you primary network interface instead of the virtual bastille0 interface as well if you know what you’re doing.

I need to add this to the official documentation.  @cedwards  is there any other systems we should document how to migrate from to bastille????

**Comment by bmac2** [comment]
will add migration section to the docs at   https://bastille.readthedocs.io/en/latest/copyright.html

**Comment by bmac2** [comment]
PR to docs submitted.  Closing.

**Comment by bmac2** [comment]
added closing as done.

**Comment by tobiastom** [comment]
Just for reference, this is the related pull request: https://github.com/BastilleBSD/bastille/pull/616
