### ISSUE TITLE
Is there a mandatory type of license for a public template ?

### ISSUE THREAD

**Issue by okalm** [BastilleBSD/bastille#600]
The title says it all, I don't know if the license matters for a template made for myself but being public.  
Most of the time I go with the The Unlicensed or WTFPL because I prefer that, I just wonder if it's okay or if I should stick to the BSD-3-Clause license used by Bastille?

**Comment by yaazkal** [comment]
Keeping it public means it can be used by anyone, so that's already not just for yourself.

Anyway, not sure if anyone here can give you a correct answer. Note that WTFPL it's also a license, can't tell if it's compatible or not with the BSD-3 license of the main project. I guess it does not matter, but not sure since I'm not a lawyer.

I do personally stay with the same BSD-3 license for all my templates, I usually use the same license as the main project in general, but I think that a better place to ask is at https://opensource.stackexchange.com since it's a general question.

Regards

**Comment by sveeke** [comment]
BastilleBSD itself is BSD-3-Clause licensed. This means that if the template you create is not part of (a fork of) BastilleBSD itself, then it's fine to use whatever license you like. But do note that if you would fork or reuse (parts of) BastilleBSD that you should at least make sure the copyright notices and the license's disclaimers of warranty are maintained.

For templates I think it's best to use very open licenses so many people can use them and improve/expand upon them :).
