### ISSUE TITLE
Bastillefile creates new variable when using $(openssl rand -base64 15) ARG

### ISSUE THREAD

**Issue by tschettervictor** [BastilleBSD/bastille#706]
**[MANDATORY] Describe the bug [MANDATORY]**
I'm trying to make the Bastillefile work with a random openssl string for an ARG variable. See the Bastillefile for Apache Guacamole [https://gitlab.com/bastillebsd-templates/guacamole/-/blob/main/Bastillefile?ref_type=heads](url)

The issue is that every time the ARG is called in the Bastillefile, it will generate and use a new random string. I would like it to generate it one time and continue using it throughout the Bastillefile.

My solution right now is to create the random ARG, `echo` it into a file, and `cat` the file to retrieve the variable. When writing standard `sh` scripts, the variable is always the same. See [https://github.com/tschettervictor/truenas-iocage-guacamole/blob/main/guacamole-jail.sh](url)

Is there a way to achieve a similar result when using the Bastillefile without the workaround I'm currently using?

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
FreeBSD 13.3-p2 jail and bastille version 0.10.20231125

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**Comment by yaazkal** [comment]
Removing the bug label as it is not.

The scripts are usually the way to go in this kind of scenario, you can check [wordpress](https://gitlab.com/bastillebsd-templates/wordpress) template as an example in order to see how it uses the script when applying the template so you don't have to copy and run the script manually later.

Depending on your taste, an alternative is to save that random string only in the first execution using a `CMD` statement like this in your Bastillefile and then reading that file in your script:

`CMD if [ ! -e /root/.my_random_string ];then openssl rand -base64 15 > /root/.my_random_string; fi`

I suggest a dotted file in order to keep it hided and to remember to not remove it from the jail.

**Comment by tschettervictor** [comment]
This is fine, as that looks like the only option. Still it would be nice to have the Bastillefile remember the ARG for the duration of the template bootstrap…

**Comment by tschettervictor** [comment]
The wordpress approach is rather neat, although it requires writing a Bastillefile and a script. But the Bastillefile would be for the major commands, then the script can be used to generate passwords and such.
