### ISSUE TITLE
[BUG] Alternative default `bastille_zfs_prefix`

### ISSUE THREAD

**Issue by MamoruDS** [BastilleBSD/bastille#713]
**Is your feature request related to a problem? Please describe.**

The current default value of `bastille_zfs_prefix` has been changed(#711) to `${bastille_zfs_zpool}/bastille`. Since all the scripts use `${bastille_zfs_zpool}/${bastille_zfs_prefix}` as the dataset path prefix, this causes a duplication of `bastille_zfs_zpool` (which will be `zroot/zroot/bastille` after `setup` without any modification).

**Describe the solution you'd like**

To avoid this issue, manually change the config value of `bastille_zfs_prefix` to an arbitrary value (e.g., the previous `bastille`). Reverting to `bastille` as the default may provide a smoother experience.

**Additional context**

An example in `bootstrap.sh` shows the script using `${bastille_zfs_zpool}/${bastille_zfs_prefix}` as the dataset path:

https://github.com/BastilleBSD/bastille/blame/cee6f20aa5c228e7e4791bc9d0fcdc412bab71ae/usr/local/share/bastille/bootstrap.sh#L150

**Comment by yaazkal** [comment]
Thanks for the comment and the workaround, I'm gonna take this

**Comment by tschettervictor** [comment]
There might need to be a variable added here.

Say someone wants to run Bastille on pool/dataset1/dataset2. The only way to make this work is by setting the `zpool` variable to `pool/dataset1/dataset2` which is confusing because datasets are datasets and not pools.

Since the code has already been written to use only those two variables, one could just update the docs to let people know that `zpool` needs to be the full zfs path to the dataset where Bastille will reside. Otherwise it will always just default to “poolname/bastille”

the alternative of course is to submit #729 and add documentation telling people to set `bastille_zfs_prefix` to whichever dataset the want below the `bastille_zfs_zpool` with /bastille at the end.

**Comment by yaazkal** [comment]
@MamoruDS thanks for the report, PR https://github.com/BastilleBSD/bastille/pull/738 should fix it and it's now merged to the `master` branch.

@tschettervictor I guess `bastille_zfs_prefix` is where the dataset and path should reside in order to not create another variable that can end up touching a lot of files and maybe inserting some unwanted errors in the way. Are you willing to create a PR for the documentation?

**Comment by tschettervictor** [comment]
I'll give it a go, sure.

**Comment by tschettervictor** [comment]
#739

**Comment by yaazkal** [comment]
Closing this issue as the fix has been merged previously
