### ISSUE TITLE
Template SERVICE

### ISSUE THREAD

**Issue by brumgeek** [BastilleBSD/bastille#93]
I have been creating some test templates, one is a node.js app if I do npm insall -g appname in CMD, and then add it as a service it will start fine from restart of container or console.

If I add SERVICE and the app start it can't start as CMD runs after SERVICE.

Would it be better to change the order of template creation so SERVICE runs last?

**Comment by cedwards** [comment]
I have been thinking about options to define a custom order for template execution. No code yet, but I have some ideas.

In your use-case is it simpler to remove (skip) SERVICE and start the service in CMD as you've done?

**Comment by brumgeek** [comment]
Skip would work, what I had to do was set up the jail, then create the service by hand.
Allowing the user to define a custom order for template execution would be better for this use case as I could have CMD run before SERVICE.

Maybe you could have another file in the template that definies custom execution order?
If that file wasn't in the template it would just run the template in the normal execution order.

**Comment by cedwards** [comment]
Please have a look at the latest template syntax particularly the `Bastillefile` which now allows any-order scripting.

**Comment by chriswells0** [comment]
I'm surely biased toward the `Bastillefile`, but it's worth noting that you should also be able to change the execution order now that #218 is merged:

`HOOKS='LIMITS INCLUDE PRE FSTAB PF PKG OVERLAY CONFIG SYSRC CMD SERVICE' bastille template folsom username/base`

I didn't actually test that, but #218 uses the existing value of `HOOKS` if it's set and the default order otherwise.
